"""make staff_id nullable

Revision ID: 0f08af78cf48
Revises: 7b970b582abc
Create Date: 2025-05-24 20:50:59.706338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f08af78cf48'
down_revision: Union[str, None] = '7b970b582abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'staff_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'staff_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
