"""added more informatii

Revision ID: 327ab12cb7ef
Revises: d18e379c620b
Create Date: 2025-05-25 02:46:36.791309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327ab12cb7ef'
down_revision: Union[str, None] = 'd18e379c620b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('summary_electricity', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('avg_monthly_electricity', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('max_monthly_electricity', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('min_monthly_electricity', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('electricity_per_sqm', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('electricity_per_person', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'electricity_per_person')
    op.drop_column('clients', 'electricity_per_sqm')
    op.drop_column('clients', 'min_monthly_electricity')
    op.drop_column('clients', 'max_monthly_electricity')
    op.drop_column('clients', 'avg_monthly_electricity')
    op.drop_column('clients', 'summary_electricity')
    # ### end Alembic commands ###
