"""added clients

Revision ID: 7b970b582abc
Revises: 185b80aadd19
Create Date: 2025-05-24 20:06:40.608069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b970b582abc'
down_revision: Union[str, None] = '185b80aadd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_commercial', sa.Boolean(), nullable=True),
    sa.Column('home_type', sa.Text(), nullable=True),
    sa.Column('home_area', sa.Float(), nullable=True),
    sa.Column('season_index', sa.Float(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('frod_state', sa.Text(), nullable=True),
    sa.Column('frod_procentage', sa.Float(), nullable=True),
    sa.Column('frod_yandex', sa.Text(), nullable=True),
    sa.Column('frod_avito', sa.Text(), nullable=True),
    sa.Column('frod_2gis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
