"""added polya

Revision ID: d18e379c620b
Revises: 0f08af78cf48
Create Date: 2025-05-24 21:03:34.302414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18e379c620b'
down_revision: Union[str, None] = '0f08af78cf48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('report_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'clients', 'reports', ['report_id'], ['id'])
    op.add_column('reports', sa.Column('all_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'all_count')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'report_id')
    # ### end Alembic commands ###
